version: '3.2'
services:
  mysql-cdr:
    image: mysql:5.7.21
    container_name: mysql-niiar
    restart: always
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=niiar
      - MYSQL_USER=niiar
      - MYSQL_PASSWORD=632266811
    ports:
      - 3306:3306
  app:
    build: .
    container_name: cdr-niiar
    image: call_detail_system
    volumes:
    - "${CDR_ROOT_DIRECTORY}:/home/cdr/"
    environment:
      - SPRING_PROFILES_ACTIVE=CONTAINER
    ports:
    - 8080:8080
    depends_on:
      - mysql-cdr
